# Generated by Django 5.0.1 on 2024-05-18 05:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

from django.contrib.auth import get_user_model

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        # Ensure correct dependency on user model
        ('auth', '0001_initial'),  # This may vary based on your project
    ]

    operations = [
        migrations.AddField(
            model_name='mycourse',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]



class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=50)),
                ('link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Mycourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_course', models.CharField(default='Python', max_length=50)),
                ('user_title', models.CharField(max_length=100)),
                ('user_duration', models.CharField(max_length=50)),
                ('user_link', models.URLField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
