# Generated by Django 5.0.1 on 2024-05-19 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_remove_mycourse_user_alter_mycourse_user_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='course',
            new_name='course_name',
        ),
        migrations.RenameField(
            model_name='mycourse',
            old_name='user_course',
            new_name='user_course_name',
        ),
    ]
