# Generated by Django 5.0.1 on 2024-06-05 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_note'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Note',
        ),
    ]
