# Generated by Django 5.0.1 on 2024-06-09 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_alter_mycourse_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycourse',
            name='user_course_name',
            field=models.CharField(max_length=50),
        ),
    ]
