# Generated by Django 5.0.1 on 2024-06-09 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_alter_mycourse_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mycourse',
            unique_together=set(),
        ),
    ]
